In [1]:
# import lib

import re
import pandas as pd
import numpy as np

In [2]:
# load the dataset

df = pd.read_excel("rawdata/job_listing.xlsx")

df.head()

,job_id,job_role,company,experience,salary,location,rating,reviews,key_skills,posted_on,job_link,company_link
0,181224917811,GN - Strategy - MC - SC&O - SC Digital Core Ar...,Accenture,3-6 Yrs,Not disclosed,"Hyderabad, Chennai, Bengaluru",3.9,52479 Reviews,"sap ariba,presentation skills,solution impleme...",1 Day Ago,https://www.naukri.com/job-listings-gn-strateg...,https://www.naukri.com/accenture-jobs-careers-...
1,181224906322,GN - SC&O - BPM - Senior Manager,Accenture,2-4 Yrs,Not disclosed,"Gurugram, Bengaluru, Delhi / NCR",3.9,52479 Reviews,"spend analysis,market research,sales and opera...",1 Day Ago,https://www.naukri.com/job-listings-gn-sc-o-bp...,https://www.naukri.com/accenture-jobs-careers-...
2,181224906320,GN - SC&O - S&P - CLM - Associate Manager,Accenture,1-5 Yrs,Not disclosed,"Gurugram, Bengaluru, Delhi / NCR",3.9,52479 Reviews,"Sourcing,PowerBI,procurement,digital sourcing,...",1 Day Ago,https://www.naukri.com/job-listings-gn-sc-o-s-...,https://www.naukri.com/accenture-jobs-careers-...
3,181224904080,GN - SONG - Service - Command Center of Future...,Accenture,12-15 Yrs,Not disclosed,"New Delhi, Gurugram, Bengaluru",3.9,52479 Reviews,"cloud solutions,WFM solutions,AI,Customer Enga...",1 Day Ago,https://www.naukri.com/job-listings-gn-song-se...,https://www.naukri.com/accenture-jobs-careers-...
4,181224904079,GN - SC&O - S&P - CLM - Manager,Accenture,8-13 Yrs,Not disclosed,"New Delhi, Gurugram, Bengaluru",3.9,52479 Reviews,"Procurement,Sourcing,Supply Chain Management,p...",1 Day Ago,https://www.naukri.com/job-listings-gn-sc-o-s-...,https://www.naukri.com/accenture-jobs-careers-...

In [3]:
# check the dataset

print("Number of rows and columns:", df.shape)

print("\nColumn names:")
print(df.columns.tolist())

Number of rows and columns: (61773, 12)

Column names:
['job_id', 'job_role', 'company', 'experience', 'salary', 'location', 'rating', 'reviews', 'key_skills', 'posted_on', 'job_link', 'company_link']

In [4]:
# check data types and missing values

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61773 entries, 0 to 61772
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   job_id        61773 non-null  int64
 1   job_role      61773 non-null  object
 2   company       41025 non-null  object
 3   experience    60154 non-null  object
 4   salary        61773 non-null  object
 5   location      60663 non-null  object
 6   rating        41029 non-null  float64
 7   reviews       41029 non-null  object
 8   key_skills    61279 non-null  object
 9   posted_on     61773 non-null  object
 10  job_link      61773 non-null  object
 11  company_link  41027 non-null  object
dtypes: float64(1), int64(1), object(10)
memory usage: 5.7+ MB

In [5]:
# check duplicate rows

df.duplicated().sum()

np.int64(1185)

In [6]:
# remove duplicate rows

df = df.drop_duplicates()

print("Shape after removing duplicates:", df.shape)

Shape after removing duplicates: (60588, 12)

In [7]:
# check missing values

df.isnull().sum()

job_id              0
job_role            0
company         20329
experience       1573
salary              0
location         1084
rating          20325
reviews         20325
key_skills        474
posted_on           0
job_link            0
company_link    20327
dtype: int64

In [8]:
# check column names

print(df.columns.tolist())

['job_id', 'job_role', 'company', 'experience', 'salary', 'location', 'rating', 'reviews', 'key_skills', 'posted_on', 'job_link', 'company_link']

In [9]:
# check salary values

df["salary"].head(20)

0        Not disclosed
1        Not disclosed
2        Not disclosed
3        Not disclosed
4        Not disclosed
5        Not disclosed
6        Not disclosed
7        Not disclosed
8        Not disclosed
9        Not disclosed
10       Not disclosed
11       Not disclosed
12       Not disclosed
13       Not disclosed
14       Not disclosed
15       Not disclosed
16       Not disclosed
17    5.5-15.5 Lacs PA
18       Not disclosed
19        8-18 Lacs PA
Name: salary, dtype: object

In [10]:
# check data types and missing values

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 60588 entries, 0 to 61772
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   job_id        60588 non-null  int64
 1   job_role      60588 non-null  object
 2   company       40259 non-null  object
 3   experience    59015 non-null  object
 4   salary        60588 non-null  object
 5   location      59504 non-null  object
 6   rating        40263 non-null  float64
 7   reviews       40263 non-null  object
 8   key_skills    60114 non-null  object
 9   posted_on     60588 non-null  object
 10  job_link      60588 non-null  object
 11  company_link  40261 non-null  object
dtypes: float64(1), int64(1), object(10)
memory usage: 6.0+ MB

In [11]:
# check missing values

missing_values = df.isnull().sum()

missing_values

job_id              0
job_role            0
company         20329
experience       1573
salary              0
location         1084
rating          20325
reviews         20325
key_skills        474
posted_on           0
job_link            0
company_link    20327
dtype: int64

In [12]:
# handle missing values

df["company"] = df["company"].fillna("Unknown")
df["experience"] = df["experience"].fillna("Not specified")
df["location"] = df["location"].fillna("Unknown")
df["rating"] = df["rating"].fillna(0)
df["reviews"] = df["reviews"].fillna(0)
df["key_skills"] = df["key_skills"].fillna("Not specified")
df["company_link"] = df["company_link"].fillna("Not available")

In [13]:
# verify missing values

df.isnull().sum()

job_id          0
job_role        0
company         0
experience      0
salary          0
location        0
rating          0
reviews         0
key_skills      0
posted_on       0
job_link        0
company_link    0
dtype: int64

In [14]:
# check salary values

df["salary"].value_counts().head(20)

salary
Not disclosed       42080
3-5 Lacs PA           337
3-6 Lacs PA           334
Unpaid                313
2-3 Lacs PA           300
2-4 Lacs PA           276
3-4 Lacs PA           230
4-6 Lacs PA           221
2.5-3.5 Lacs PA       221
2.5-3 Lacs PA         216
2-5 Lacs PA           209
2-3.5 Lacs PA         195
3-4.5 Lacs PA         193
10-20 Lacs PA         188
2.5-4 Lacs PA         178
50,000-3 Lacs PA      161
15-25 Lacs PA         158
3-8 Lacs PA           152
4-5 Lacs PA           150
3-3.5 Lacs PA         147
Name: count, dtype: int64

In [15]:
# extract minimum and maximum salary

def extract_salary(salary):
    salary = str(salary).lower().strip()

    if "not disclosed" in salary:
        return pd.Series([np.nan, np.nan])

    numbers = re.findall(r"\d+(?:\.\d+)?", salary)

    if len(numbers) >= 2:
        return pd.Series([float(numbers[0]), float(numbers[1])])
    elif len(numbers) == 1:
        return pd.Series([float(numbers[0]), float(numbers[0])])
    else:
        return pd.Series([np.nan, np.nan])


df[["min_salary_lpa", "max_salary_lpa"]] = df["salary"].apply(extract_salary)

df[["salary", "min_salary_lpa", "max_salary_lpa"]].head(20)

              salary  min_salary_lpa  max_salary_lpa
0      Not disclosed             NaN             NaN
1      Not disclosed             NaN             NaN
2      Not disclosed             NaN             NaN
3      Not disclosed             NaN             NaN
4      Not disclosed             NaN             NaN
5      Not disclosed             NaN             NaN
6      Not disclosed             NaN             NaN
7      Not disclosed             NaN             NaN
8      Not disclosed             NaN             NaN
9      Not disclosed             NaN             NaN
10     Not disclosed             NaN             NaN
11     Not disclosed             NaN             NaN
12     Not disclosed             NaN             NaN
13     Not disclosed             NaN             NaN
14     Not disclosed             NaN             NaN
15     Not disclosed             NaN             NaN
16     Not disclosed             NaN             NaN
17  5.5-15.5 Lacs PA             5.5            15.5
18     Not disclosed             NaN             NaN
19      8-18 Lacs PA             8.0            18.0

In [16]:
# check salary conversion

print("Minimum salary available:", df["min_salary_lpa"].notna().sum())
print("Maximum salary available:", df["max_salary_lpa"].notna().sum())
print("Salary not disclosed:", df["min_salary_lpa"].isna().sum())

Minimum salary available: 18195
Maximum salary available: 18195
Salary not disclosed: 42393

In [17]:
# check experience values

df["experience"].value_counts().head(20)

experience
5-10 Yrs         4478
3-8 Yrs          3323
2-5 Yrs          2557
2-7 Yrs          2326
3-5 Yrs          2222
1-3 Yrs          2165
1-6 Yrs          1988
0-5 Yrs          1954
3-7 Yrs          1919
4-9 Yrs          1716
0-2 Yrs          1699
1-5 Yrs          1628
7-12 Yrs         1621
Not specified    1573
1-4 Yrs          1556
2-4 Yrs          1474
3-6 Yrs          1471
0-1 Yrs          1448
5-8 Yrs          1439
2-6 Yrs          1325
Name: count, dtype: int64

In [18]:
# extract minimum and maximum experience

def extract_experience(experience):
    experience = str(experience).lower().strip()

    numbers = re.findall(r"\d+(?:\.\d+)?", experience)

    if len(numbers) >= 2:
        return pd.Series([float(numbers[0]), float(numbers[1])])
    elif len(numbers) == 1:
        return pd.Series([float(numbers[0]), float(numbers[0])])
    else:
        return pd.Series([np.nan, np.nan])


df[["min_experience_years", "max_experience_years"]] = df["experience"].apply(
    extract_experience
)

df[["experience", "min_experience_years", "max_experience_years"]].head(20)

   experience  min_experience_years  max_experience_years
0     3-6 Yrs                   3.0                   6.0
1     2-4 Yrs                   2.0                   4.0
2     1-5 Yrs                   1.0                   5.0
3   12-15 Yrs                  12.0                  15.0
4    8-13 Yrs                   8.0                  13.0
5    9-13 Yrs                   9.0                  13.0
6     5-9 Yrs                   5.0                   9.0
7    5-10 Yrs                   5.0                  10.0
8   10-16 Yrs                  10.0                  16.0
9   11-16 Yrs                  11.0                  16.0
10    2-5 Yrs                   2.0                   5.0
11    0-4 Yrs                   0.0                   4.0
12    0-4 Yrs                   0.0                   4.0
13   6-10 Yrs                   6.0                  10.0
14    4-8 Yrs                   4.0                   8.0
15   8-13 Yrs                   8.0                  13.0
16   8-13 Yrs                   8.0                  13.0
17    3-8 Yrs                   3.0                   8.0
18    3-8 Yrs                   3.0                   8.0
19   5-10 Yrs                   5.0                  10.0

In [19]:
# check experience conversion

print("Minimum experience available:", df["min_experience_years"].notna().sum())
print("Maximum experience available:", df["max_experience_years"].notna().sum())
print("Experience not available:", df["min_experience_years"].isna().sum())

Minimum experience available: 59015
Maximum experience available: 59015
Experience not available: 1573

In [20]:
# check job roles

df["job_role"].value_counts().head(20)

job_role
Application Developer                    1939
Application Lead                         1020
Sales Executive                           288
Software Development Engineer             263
Business Development Executive            256
Business Development Manager              185
Sales Manager                             173
Application Tech Support Practitioner     164
Java Developer                            155
Application Support Engineer              139
Application Designer                      135
Graphic Designer                          119
Accountant                                115
Senior Software Engineer                  111
Data Engineer                             111
Software Engineer                         108
Relationship Manager                      107
Business Analyst                          105
Area Sales Manager                        101
Project Manager                           100
Name: count, dtype: int64

In [21]:
# standardize job titles

df["job_role"] = (
    df["job_role"]
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
    .str.title()
)

df["job_role"].head(20)

0     Gn - Strategy - Mc - Sc&O - Sc Digital Core Ar...
1                      Gn - Sc&O - Bpm - Senior Manager
2             Gn - Sc&O - S&P - Clm - Associate Manager
3     Gn - Song - Service - Command Center Of Future...
4                       Gn - Sc&O - S&P - Clm - Manager
5                   R&R Fs - Python Full Stack -Manager
6          R&R Fs - Python Full Stack -Senior Associate
7                          R&R Fs-Reg Reporting-Manager
8                             Sr Advanced Embedded Engr
9                             Sr Advanced Embedded Engr
10                                 Sales Ops Specialist
11                                            Mbbs, Dvd
12                                           Mbbs, Ddvl
13                      Rest Assured With Java Selenium
14                           Talent Sourcer - Emea/Apac
15                Ax/D365 Finance Functional Consultant
16                         Ax/D365 Technical Consultant
17                                 Hiring For Mes Pas-X
18    Selenium With Python -Contract To Hire-Chennai...
19                                       Java Developer
Name: job_role, dtype: object

In [22]:
# check locations

df["location"].value_counts().head(20)

location
Bengaluru                                                          8370
Pune                                                               3951
Hyderabad                                                          3818
Chennai                                                            3331
Gurugram                                                           3134
Mumbai                                                             2915
Noida                                                              2401
Ahmedabad                                                          1420
Kolkata                                                            1225
Kolkata, Mumbai, New Delhi, Hyderabad, Pune, Chennai, Bengaluru    1092
Unknown                                                            1084
Remote                                                              976
Coimbatore                                                          920
Jaipur                                                              744
Kochi                                                               396
Vadodara                                                            389
Hybrid - Bengaluru                                                  379
Navi Mumbai                                                         346
Thane                                                               289
Nagpur                                                              256
Name: count, dtype: int64

In [23]:
# standardize locations

df["location"] = (
    df["location"]
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
    .str.title()
)

df["location"].head(20)

0                    Hyderabad, Chennai, Bengaluru
1                 Gurugram, Bengaluru, Delhi / Ncr
2                 Gurugram, Bengaluru, Delhi / Ncr
3                   New Delhi, Gurugram, Bengaluru
4                   New Delhi, Gurugram, Bengaluru
5                             Hyderabad, Bengaluru
6                             Hyderabad, Bengaluru
7                             Hyderabad, Bengaluru
8                         Greater Noida, Bengaluru
9                         Greater Noida, Bengaluru
10                        Greater Noida, Bengaluru
11                           Bengaluru, Aurangabad
12                           Bengaluru, Aurangabad
13          Hybrid - Hyderabad, Chennai, Bengaluru
14                    Hybrid - Gurugram, Bengaluru
15      Hybrid - Hyderabad, Bengaluru, Delhi / Ncr
16      Hybrid - Hyderabad, Bengaluru, Delhi / Ncr
17                   Hyderabad, Chennai, Bengaluru
18          Hybrid - Hyderabad, Chennai, Bengaluru
19    Hybrid - Hyderabad, Bangalore Rural, Chennai
Name: location, dtype: object

In [24]:
# check key skills

df["key_skills"].head(20)

0     sap ariba,presentation skills,solution impleme...
1     spend analysis,market research,sales and opera...
2     Sourcing,PowerBI,procurement,digital sourcing,...
3     cloud solutions,WFM solutions,AI,Customer Enga...
4     Procurement,Sourcing,Supply Chain Management,p...
5     Data analysis,Data management,Analytical,Consu...
6     Data analysis,Automation,Analytical,Consulting...
7     Data analysis,Automation,Data management,Busin...
8     RTOS,Test case execution,C++,Linux,Programming...
9     Software testing,RTOS,Test case execution,C++,...
10    Computer science,Team management,Analytical,Sa...
11         DVD - (Aurangabad,Bangalore),Dr) MBBS,DR,DVD
12               Bangalore),Dr) MBBS,DDVL - (Aurangabad
13    Rest Assured,Java Selenium,Testing,Selenium,Ja...
14    Sourcing Profiles,Talent Sourcing,Talent Acqui...
15    Functional,D365,Finance,General Ledger,Fixed A...
16    D365,X++,Axapta,Coding,AX,Microsoft Dynamics A...
17                               MES,PAS-X,WERUM,Hiring
18                        python,selenium,SQL,Contracts
19    Spring Boot,API,Microservices,Spring,Boot,Java...
Name: key_skills, dtype: object

In [25]:
# split multiple skills

df["key_skills"] = df["key_skills"].str.split(",")

df["key_skills"].head(10)

0    [sap ariba, presentation skills, solution impl...
1    [spend analysis, market research, sales and op...
2    [Sourcing, PowerBI, procurement, digital sourc...
3    [cloud solutions, WFM solutions, AI, Customer ...
4    [Procurement, Sourcing, Supply Chain Managemen...
5    [Data analysis, Data management, Analytical, C...
6    [Data analysis, Automation, Analytical, Consul...
7    [Data analysis, Automation, Data management, B...
8    [RTOS, Test case execution, C++, Linux, Progra...
9    [Software testing, RTOS, Test case execution, ...
Name: key_skills, dtype: object

In [26]:
# clean individual skills

df["key_skills"] = df["key_skills"].apply(
    lambda skills: [
        skill.strip().title()
        for skill in skills
        if skill.strip()
    ] if isinstance(skills, list) else skills
)

df["key_skills"].head(10)

0    [Sap Ariba, Presentation Skills, Solution Impl...
1    [Spend Analysis, Market Research, Sales And Op...
2    [Sourcing, Powerbi, Procurement, Digital Sourc...
3    [Cloud Solutions, Wfm Solutions, Ai, Customer ...
4    [Procurement, Sourcing, Supply Chain Managemen...
5    [Data Analysis, Data Management, Analytical, C...
6    [Data Analysis, Automation, Analytical, Consul...
7    [Data Analysis, Automation, Data Management, B...
8    [Rtos, Test Case Execution, C++, Linux, Progra...
9    [Software Testing, Rtos, Test Case Execution, ...
Name: key_skills, dtype: object

In [27]:
# create separate skills dataset

skills_df = df[["job_id", "key_skills"]].explode("key_skills")

skills_df.head(10)

         job_id               key_skills
0  181224917811                Sap Ariba
0  181224917811      Presentation Skills
0  181224917811  Solution Implementation
0  181224917811                    Ariba
0  181224917811                    Tower
0  181224917811    Management Consulting
0  181224917811       Project Management
0  181224917811                      Sap
1  181224906322           Spend Analysis
1  181224906322          Market Research

In [28]:
# count most demanded skills

top_skills = skills_df["key_skills"].value_counts().head(20)

top_skills

key_skills
Sales                   5541
Management              5436
Project Management      3452
Sap                     3286
Python                  2675
Customer Service        2422
Analytical              2123
Javascript              2109
Css                     1920
Development             1919
Agile                   1883
Communication Skills    1850
Troubleshooting         1825
Consulting              1824
Sql                     1793
Oracle                  1705
Automation              1681
Java                    1576
Operations              1494
Business Development    1475
Name: count, dtype: int64

In [29]:
# check companies with most job postings

top_companies = df["company"].value_counts().head(20)

top_companies

company
Unknown                                    20329
Accenture                                   6011
Genpact                                      820
Jio                                          542
Bajaj Finserv Ltd.                           472
IBM                                          461
EY                                           437
Cognizant                                    434
Infosys                                      355
Capgemini                                    258
W Goa                                        237
2coms                                        214
Pricewaterhouse Coopers Private Limited      209
Adani Group                                  191
Deutsche Bank                                164
Virtusa                                      153
Diensten Tech Limited                        150
Facilities And Building Solutions            143
Tata Capital                                 142
Teleperformance (TP)                         132
Name: count, dtype: int64

In [30]:
# save cleaned dataset

df.to_csv("cleaned_job_listing.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [31]:
# verify cleaned dataset

print("Cleaned dataset shape:", df.shape)

df.head()

Cleaned dataset shape: (60588, 16)

,job_id,job_role,company,experience,salary,location,rating,reviews,key_skills,posted_on,job_link,company_link,min_salary_lpa,max_salary_lpa,min_experience_years,max_experience_years
0,181224917811,Gn - Strategy - Mc - Sc&O - Sc Digital Core Ar...,Accenture,3-6 Yrs,Not disclosed,"Hyderabad, Chennai, Bengaluru",3.9,52479 Reviews,"[Sap Ariba, Presentation Skills, Solution Impl...",1 Day Ago,https://www.naukri.com/job-listings-gn-strateg...,https://www.naukri.com/accenture-jobs-careers-...,NaN,NaN,3.0,6.0
1,181224906322,Gn - Sc&O - Bpm - Senior Manager,Accenture,2-4 Yrs,Not disclosed,"Gurugram, Bengaluru, Delhi / Ncr",3.9,52479 Reviews,"[Spend Analysis, Market Research, Sales And Op...",1 Day Ago,https://www.naukri.com/job-listings-gn-sc-o-bp...,https://www.naukri.com/accenture-jobs-careers-...,NaN,NaN,2.0,4.0
2,181224906320,Gn - Sc&O - S&P - Clm - Associate Manager,Accenture,1-5 Yrs,Not disclosed,"Gurugram, Bengaluru, Delhi / Ncr",3.9,52479 Reviews,"[Sourcing, Powerbi, Procurement, Digital Sourc...",1 Day Ago,https://www.naukri.com/job-listings-gn-sc-o-s-...,https://www.naukri.com/accenture-jobs-careers-...,NaN,NaN,1.0,5.0
3,181224904080,Gn - Song - Service - Command Center Of Future...,Accenture,12-15 Yrs,Not disclosed,"New Delhi, Gurugram, Bengaluru",3.9,52479 Reviews,"[Cloud Solutions, Wfm Solutions, Ai, Customer ...",1 Day Ago,https://www.naukri.com/job-listings-gn-song-se...,https://www.naukri.com/accenture-jobs-careers-...,NaN,NaN,12.0,15.0
4,181224904079,Gn - Sc&O - S&P - Clm - Manager,Accenture,8-13 Yrs,Not disclosed,"New Delhi, Gurugram, Bengaluru",3.9,52479 Reviews,"[Procurement, Sourcing, Supply Chain Managemen...",1 Day Ago,https://www.naukri.com/job-listings-gn-sc-o-s-...,https://www.naukri.com/accenture-jobs-careers-...,NaN,NaN,8.0,13.0